previews:
  generation: automatic
services:
- type: web
  runtime: docker
  name: focus-ai-api
  plan: free
  previews:
    plan: free
  numInstances: 1
  dockerfilePath: apps/backend/Dockerfile
  buildFilter:
    paths:
      - apps/backend/**
      - packages/python/**
  envVars:
    - fromGroup: Focus-Environment
    - key: SERVICE_TYPE
      value: api
    - key: API_URL
      value: https://focus-backend-api.onrender.com
    - key: AI_URL
      value: https://focus-ai-api.onrender.com
    - key: JOB_DOMAIN
      value: training

- type: worker
  runtime: docker
  name: focus-ai-worker
  plan: free
  previews:
    plan: free
  numInstances: 1
  dockerfilePath: apps/ai/Dockerfile
  buildFilter:
    paths:
      - apps/ai/**
      - packages/python/**
  envVars:
    - fromGroup: Focus-Environment
    - key: SERVICE_TYPE
      value: worker
    - key: API_URL
      value: https://focus-backend-api.onrender.com
    - key: AI_URL
      value: https://focus-ai-api.onrender.com
    - key: JOB_DOMAIN
      value: training
